site_name: mcNOTE
site_url: https://mydominan.org/mysite
repo_url: https://github.com/MC115-UIT/mcnote
repo_name: MC115-UIT/mcnote
theme:
  name: material
  font:
    text: Roboto Mono
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/git-alt
  logo: assets/logo-nbg.png
  favicon: assets/logo-nbg.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary : black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.footer
  #  - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.code.copy
    - content.code.select
plugins:
    - search
    - tags:
        tags_file: tags.md
    - blog
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://fb.com/tuilacuongg
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - attr_list
    - md_in_html
nav:
  - Home: index.md
  - Code Docs:
    - .NET: 
      - Daily note : coding/NET/daily-note.md
      - Helper : coding/NET/helper.md
      - Research : coding/NET/research.md
      - Interview : coding/NET/interviewing.md
      - Coding-pattern : coding/NET/pattern-approach.md
    - Data engineer: 
      - ETL :
        - Sale-mart project : coding/DE/ETL/Sale-mart-sample.md
      - Daily note : coding/DE/daily-note.md
      - Helper : coding/DE/helper.md
  - About:
    - About me: about/about.md
    - Childhood: about/childhood.md
    - Portfolito: about/portfolito.md
  - Tags: tags.md
  - Blog:
    - blog/index.md
copyright: Copyright &copy; 2024 - 2099 Minh Cuong

